@url = http://localhost:5000
@customerTestId = e6d9df37-48ce-4d6b-bec7-a64894d87419
###
GET {{url}}/api/customers

###
POST {{url}}/api/customers
Content-Type: application/json

{
  "id": "{{customerTestId}}",
  "name": "Alex",
  "address": "US"
}

###
GET {{url}}/api/customers/{{customerTestId}}

###
PUT {{url}}/api/customers/{{customerTestId}}
Content-Type: application/json

{
  "id": "{{customerTestId}}",
  "name": "Alex Ferguson",
  "address": "UK"
}

###
DELETE {{url}}/api/customers/{{customerTestId}}